---
title: "Rmd-Files -- on R Markdown"
author: "Martin Papenberg"
---

Lately, I have been trying to create all of my documents (presentations, manuscripts,
examinations...) using R Markdown. While R Markdown is incredibly useful, it has its
limitations. In particular, R Markdown is relying on functionality of other software
(Latex, pandoc), which sometimes need to be addressed directly to achieve your goal.

Below are some texts on my journey with R Markdown and the difficulties that I dealt
with. I do not claim to be an expert on R Markdown; I am simply writing about stuff
that I found curious. Usually I found solutions by googling and trial and error --
there is no garantee that presented solutions are optimal. If you wish to learn about
R Markdown in general, check out <a href="http://rmarkdown.rstudio.com/"
target="_blank"> RStudio's rmarkdown documentation</a>. <a
href="https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf"
target="_blank">This cheat sheet</a> is also very useful.

### Posts:

- <a href="positionbeamer.html">Positioning content at the top of a R Markdown Beamer
  slide</a>
- <a href="modifytemplate.html">Modifying the default R Markdown template</a>
- <a href="usingrmarkdown.html">Installing R Markdown and papaja on Ubuntu</a>

### Upcoming:

- Use a theme to create R Markdown Beamer slides
- Adding a short title for Beamer slides
- Embedding pandoc commands in a R Markdown file
- Suppress automatic numbering of figures
- Use {.allowframebreaks} to show the complete reference list in Beamer slides
- Add whitespace to a Beamer slide
- Which editors support R Markdown syntax highlighting?
- Detrimental whitespace in YAML headers
- Tables in R Markdown pdf (formatting is difficult in markdown)

