---
title: "Installing R Markdown and papaja on Ubuntu (without RStudio)"
date: August 03, 2016
author: Martin Papenberg
---

<a href="https://github.com/crsh/papaja" target ="_blank">papaja</a> is template for
<a href="http://rmarkdown.rstudio.com/" target="_blank">R Markdown</a>, which is used
to create APA 6th conform journal articles. papaja is most easily used in integration
with the <a href="http://www.rstudio.com/" target="_blank">RStudio</a> IDE to convert
formatted text and <a href="http://www.r-project.org/" target ="_blank">R code</a>
and to .html, .pdf, etc. This is a good thing: RStudio is free, open source and
offers useful features; it is the prefered IDE for many R enthusiasts that I
know. However, RStudio is not everyone's coding environment of choice. If you wish to
use RMarkdown and papaja to create your APA articles, you probably want to use your
most comfortable R environment (other choices might be <a
href="http://ess.r-project.org/" target="_blank">emacs ESS</a> or <a
href="https://rkward.kde.org/" target="_blank">rkward</a>).

papaja (and R Markdown) make use of a bunch of open source software in order to
convert a simple .Rmd file to pdf manuscripts. In RStudio, most of these dependencies
do not need to be installed manually as they come with the installation package. This
repository contains guidelines on how to install R Markdown and papaja on an Ubuntu
system without the requirement of an RStudio installation, which is
somewhat less convenient (but maybe worthy). There is no warranty that it will work
the same way on your system, it is just an explanation of how I did it. I wanted to
share this because I found it somewhat tricky to make papaja run outside of RStudio.

Note: To install the required dependencies for papaja, terminal commands are given
that will install these dependencies. Commands starting with `$` must be typed in
your normal terminal. Commands starting with `>` must be executed in your R console.


### 1) Install the required TeX packages
-- as described in the papaja GitHub repository:

```
$ sudo apt install texlive texlive-latex-extra texlive-bibtex-extra texlive-publishers texlive-fonts-recommended texlive-fonts-extra texlive-humanities
```

### 2) Install some required GNU libraries

If these libraries are not available on your system, install them. They are required
to install the `devtools` package that we need to install papaja:

```
$ sudo apt install libcurl4-openssl-dev libxml2-dev libgsl0-dev libssl-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
```

### 3) Install the required R packages

- Make sure you have a recent version of R
    + the version in the standard Ubuntu repository is too old, which will cause some
    package dependencies installations to fail
    + update R as described here: https://cran.r-project.org/bin/linux/ubuntu/; 
    also see http://sites.psu.edu/theubunturblog/installing-r-in-ubuntu/
    + remember to install the development packages `r-base-dev`
- Install the `devtools` package (`> install.packages("devtools")`)
- Get the papaja package:

```
> devtools::install_github("crsh/papaja")
```

- some dependencies (including `rmarkdown`) are -- if not available -- automatically
  installed in the process


### 4) Install pandoc
- rmarkdown makes use of pandoc library to do its conversions between file formats
- The standard Ubuntu repo should be enough for 64 Bit installations:

```
$ sudo apt install pandoc pandoc-citeproc
```

- For 32-bit systems, consider this advice, otherwise skip to **ImageMagick**
    + <a href="http://pandoc.org/installing.html#linux"
      target="_blank">http://pandoc.org/installing.html#linux</a>
- If you are using a 32-Bit system, installing pandoc is less convenient:
    + install Haskell platform, which includes an installation tool that will install pandoc:

```
$ sudo apt install haskell-platform
```
    
- Now you can use `cabal` in your terminal, an installation tool for Haskell software
- use cabal to install pandoc (and pandoc citeproc for citation processing features)

```
$ cabal update
$ cabal install pandoc pandoc-citeproc
```

- the pandoc installation process will take some time
- when the installtion has finished, add pandoc to your executable path 
- This step is crucial, otherwise R cannot call pandoc:
- add the following line to the '.profile' file in the your home directory (it is a hidden file)

```
PATH=/home/yourName/.cabal/bin:"$PATH" 
```

- (remember to change "yourName" to your user name)
- you need to log out before you can call pandoc!
- after relogin check whether your pandoc installation was successful:

```
> rmarkdown::pandoc_available()
```

- returns TRUE if your pandoc installation was successful


### 5) ImageMagick
- <a href="http://www.imagemagick.org/script/index.php"
  target="_blank">ImageMagick</a> is required to adjust image properties in your
  document (e.g. R plot size)
- install ImageMagick by:

```
$ sudo apt install imagemagick imagemagick-doc
```

### 6) Create a manuscript and enjoy

- create an .Rmd file, which contains this text in the metadata section ('YAML
  header') of your document
    + `output: papaja::apa6_pdf`
- check the example article in the <a
  href="https://github.com/crsh/papaja/tree/master/example" target="_blank">papaja
  repository</a> to learn more
- To convert your .Rmd file into an APA article, simply call the render function:

```
> rmarkdown::render("manuscript.Rmd")
```

### 7) Further reading

These are some sources on writing in R Markdown and / or papaja that might be useful:

- http://blog.efpsa.org/2015/06/09/how-not-to-worry-about-apa-style/
- http://blog.rstudio.org/2014/06/18/r-markdown-v2/
- http://kbroman.org/knitr_knutshell/pages/markdown.html
- http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html
- http://rmarkdown.rstudio.com/
- http://rmarkdown.rstudio.com/developer_document_templates.html
- https://github.com/rstudio/rmarkdown
- http://yihui.name/en/2012/06/enjoyable-reproducible-research/
- http://nicercode.github.io/guides/reports/

---

Last updated: `r Sys.Date()`

### <a href="index.html">Back to the front page</a>

&nbsp;
