---
title: "Another reason to learn programming as a researcher"
date: November 28, 2019
author: Martin Papenberg
---

A lot has been written on the reasons why researchers should learn how 
to program. I'd like to add one: If you are like me, nobody has taught 
you about the more "recent" developments in statistics, such as Bayes 
factors or linear mixed models. Now we are somehow expected to figure 
them out ourselves. This is a difficult task, but being able to program 
helps. I really only "got" Bayes factors after I implemented some myself 
in `R`, and there is still a lot I do not know. If you know about Monte 
Carlo simulations, you can try to figure out the behavior of any method 
under varying conditions, increasing your understanding of---and trust 
in---a method, even if you lack a strong mathematical background. As an 
example, see the [simulation tutorial on linear mixed models by Lisa 
DeBruine and Dale Barr](https://psyarxiv.com/xp5cy/). I am not arguing 
that programming is the optimal method for learning for everyone. But I 
do think it often helps.

---

Last updated: `r Sys.Date()`

### <a href="index.html">Back to the front page</a>

&nbsp;
