---
title: "Speeding up the `R` package anticlust"
date: April 19, 2020
author: Martin Papenberg
output:
  html_document:
    df_print: kable
---

```{r, eval = FALSE}

library(knitr)
library(dplyr)
knitr::opts_chunk$set(warning = FALSE) # echo = FALSE
options(scipen = 999, digits = 2)

knit_print.matrix = function(x, ...) {
    res = paste(c("", "", kable(x)), collapse = "\n")
    asis_output(res)
}
registerS3method("knit_print", "matrix", knit_print.matrix)


```

In this post I explore how (across the time span of 1,5 years) I sped up one of 
the main methods in my [`R` package 
anticlust](https://github.com/m-Py/anticlust)-

[Image with the running times across iterations]

1. Describe the algorithm.
2. Describe what takes time (a. computing cluster centers, b. computing distances)
3. What steps did I take to make the algorithm faster.

- Clever vectorization to compute many Euclidean distances "at the same time" 
(using a Base R function I accidentally found in a paper)
- Avoiding unnecessary repetitions of code (no input validation in each exchange 
iteration)
- Employing a local update rather than re-evaluating the objective function 
entirely for each exchange
- Rewriting it in C

Note that all of these steps did not change the asymptotic run time of the 
algorithm; the algorithm was the same all along. In R, I early implemented 
other speed optimization schemes that changed the algorithm's behaviour by 
employing fewer exchanges, which did not impair the solution quality by a lot.

In total, this took about 1,5 years to get to the current point
Takehome message: Writing fast code in R is really hard, and some things can 
hardly be sped up. E.g., it is not really possible to avoid repeated memory 
allocations across optimization iterations. In C, you have more control about 
this process. 

```R

# Speedup for N = 100, M = 2, K = 2:

# Seconds:
# non-vectorized   vectorized-1   vectorized-2   local-update              C 
#           4.10           2.96           2.43           0.25           0.00 

# Speedup factor:
# > round(times / times["C"], 2)
# non-vectorized   vectorized-1   vectorized-2   local-update              C 
#        2003.62        1447.23        1185.67         123.83           1.00 




# Speedup for N = 300, M = 10, K = 10:

# Seconds:
# non-vectorized   vectorized-1   vectorized-2   local-update              C 
#         530.92         192.27         185.00          14.19           0.07 
 
# Speedup factor:
# non-vectorized   vectorized-1   vectorized-2   local-update              C 
#        8165.14        2956.89        2845.18         218.28           1.00 


---

Last updated: `r Sys.Date()`

### <a href="index.html">Back to the front page</a>

&nbsp;
